name: GitHub - Activity - Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: HerndonE/github-activity-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.GITHUB_TOKEN }}